### ISSUE TITLE
Rspec running tests twice 

### ISSUE THREAD

**Issue by amittauro** [makersacademy/common-knowledge#246]
**Describe the situation**
I have the following code:

require_relative './../spec_runner.rb'

RSpec.describe 'Even Number count' do
  it 'counts even numbers' do
    evendigits = Even_Numbers.new
    expect(evendigits.count_even_numbers([1,2,3,4,5,6])).to eq 2
  end
end

**To Reproduce**
Steps to reproduce the behaviour:
in the terminal when I run:
$ bundle exec Rspec I get:

$ bundle exec rspec ./count_even_numbers_spec.rb
FF

Failures:

  1) Even Number count counts even numbers
     Failure/Error: expect(evendigits.count_even_numbers([1,2,3,4,5,6])).to eq 2
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./count_even_numbers_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) Even Number count counts even numbers
     Failure/Error: expect(evendigits.count_even_numbers([1,2,3,4,5,6])).to eq 2
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./count_even_numbers_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.03045 seconds (files took 0.1405 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./count_even_numbers_spec.rb[1:1] # Even Number count counts even numbers
rspec ./count_even_numbers_spec.rb[2:1] # Even Number count counts even numbers

**Expected behaviour**
I expected only one example failure. Not two. 

**Screenshots**

**Additional context**
Add any other context about the problem here

**Comment by amittauro** [comment]
Commented out the last line so doesn't re-run the spec file:

require_relative './test_framework.rb'

require_relative './count_even_numbers.rb'

#require_relative './specs/count_even_numbers_spec.rb'
